workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: docker
    repo: plugins/slack
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: My Plugin
  desc: Description of My Plugin
  type: publish|deploy|notify|clone|cache
  image: plugins/my-plugin
  labels:
    - label1
    - label2
    - label3
